 
 /*------------------------------------------------------------------------
    File        : FormParameters
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : dkurapkis
    Created     : Wed Jan 11 22:17:52 EET 2017
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS example.FormParameters: 

END CLASS.