 
 /*------------------------------------------------------------------------
    File        : BaseParameter
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : dkurapkis
    Created     : Thu Jan 12 20:02:08 EET 2017
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS BaseParameter: 

END CLASS.